

# ------------------- Deployment file specification --------------------------
apiVersion: apps/v1
kind: Deployment
metadata:
  # Unique key of the Deployment instance
  name: mongodb-same-pod
spec:
  # 3 Pods should exist at all times.
  replicas: 1
  selector:
    matchLabels:
      app: mongo-nodeui
  template:
    metadata:
      labels:
        # Apply this label to pods and default
        # the Deployment label selector to this value
        app: mongo-nodeui
    spec:
    # ------------ we just change this part for run container in same pod --------------
      containers:
      - name: mongodb-nodeui
        # Run this image
        image: yasin005/mongobd-node:07
      - name: mongo
        image: mongo:latest

---


###
##
# ------------------- services file specification --------------------------

kind: Service
apiVersion: v1
metadata:
  # Unique key of the Service instance
  name: service-mongo-nodeui
spec:
  ports:
    # Accept traffic sent to port 80
    - name: http
      port: 8080
      targetPort: 3000
  selector:
    # Loadbalance traffic across Pods matching
    # this label selector
    app: mongo-nodeui
  # Create an HA proxy in the cloud provider
  # with an External IP address - *Only supported
  # by some cloud providers*
  type: LoadBalancer



